development:
  http_monitor_host: "localhost"
  http_monitor_port: 8098
  websocket_host: "localhost"
  websocket_port: 6789
  ssl_certfile: ""
  ssl_keyfile: ""
  monitor_trigger: False
  dashboard_trigger: False
  ssl_trigger: False

production:
  http_monitor_host: "0.0.0.0"
  http_monitor_port: 8097
  websocket_host: "0.0.0.0"
  websocket_port: 8006
  ssl_certfile: "/etc/ssl/certs/bio3.crt"
  ssl_keyfile: "/etc/ssl/certs/bio3.key"
  monitor_trigger: False
  dashboard_trigger: False
  ssl_trigger: True